### PR TITLE
test added

### PR DESCRIPTION
**Pull request by adamminiuk**
- added tests
- get uniqe pokemons

### CODE REVIEW

**Comment by piecioshka** [comment]
@adamminiuk thanks a lot for pull request. I will check it tommorow ;)

**Comment by piecioshka** [comment]
I was review your changes and I am impressed! 

Thanks so much!

**Comment by piecioshka** [comment]
I wrote short post on my blog: http://piecioshka.pl/blog/2015/01/19/pokemon-js.html
@adamminiuk I used your login if you don't mind :)

**Comment by adamminiuk** [comment]
Nice post. Of course I don't mind :)

**Comment by adamminiuk** [comment]
Beers appeared on the desk. Thanks!

**Pull request merged**
